# Generated by Django 5.1.6 on 2025-02-08 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_subscription_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
