# Generated by Django 5.1.6 on 2025-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_delete_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occured_at", models.DateField()),
                ("title", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=300, unique=True)),
                ("body", models.TextField()),
                ("teacher", models.TextField()),
                (
                    "semester_key",
                    models.CharField(default="Spring 2025", max_length=50),
                ),
            ],
        ),
    ]
