# Generated by Django 5.1.6 on 2025-02-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester_key",
            field=models.CharField(default="spring-2025", max_length=50),
        ),
    ]
