# Generated by Django 5.1.6 on 2025-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_course_semester_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="overview",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
