# Generated by Django 5.1.6 on 2025-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_course_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="apply_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
