# Generated by Django 5.2 on 2025-07-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_course_apply_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester_key",
            field=models.CharField(default="fall-2025", max_length=50),
        ),
    ]
